### ISSUE TITLE
German Umlauts not rendered correctly

### ISSUE THREAD

**Issue by mannipulator** [sebnilsson/AspNetSeo#5]
Hi,

I love your package, but I have problems displaying German umlauts like Ü in the meta description.

In the NGINX server everything is set to UTF-8, and Chrome confirms this, but it is still displayed incorrectly.

If I specify it like this:

`
  [PageTitle("M&uuml;nchen")]
`
this is the result
`
 <meta name="description" content="M&#xFFFD;nchen." />
`

If I do it like this:

`  [PageTitle("München")]`
 this is what comes out:
`
 <meta name="description" content="M&#xFFFD;nchen" />`

**Comment by sebnilsson** [comment]
This looks like an configuration issue with NGINX.

The code in the package only passes native .NET/C# `string`s, so if any unexpected encoding happens, it should be in NGINX. I assume this, given that you're the first person to report this problem.

Could you double check if it works on your local machine with something else than NGINX?

**Comment by sebnilsson** [comment]
Hello @mannipulator

Thank you for the kind words.

I tried this out with my local instance and I used the umlaut U, as you mentioned and the Swedish characters of `Å`, `Ä` and `Ö`. They all have this behavior that you mention.

This seems to be the expected behavior in ASP.NET, since it works the same when I just use the Razor `@`-syntax with any string containing these kinds of characters.

**Comment by sebnilsson** [comment]
@mannipulator I can see the problem here.

The problem is that even in vanilla ASP.NET, this is the behavior.

```
@{
    var pageTitle = "ABCÅÄÖåäöÜü123";
}
/* ... */
<title>@pageTitle</title>
```

Above results in the following when doing *View source* in the browser:

`<title>ABC&#xC5;&#xC4;&#xD6;&#xE5;&#xE4;&#xF6;&#xDC;&#xFC;123</title>`

I'd prefer not to write a custom utility method which is sort of like the native HTML encode, but with some manually maintained exception list, or something like that. It's a complexity I'd like not to own.

Any suggestions for possible directions from your point of view?

**Comment by mannipulator** [comment]
@sebnilsson I made  a try with @Html.Raw and I got the following results: 

`    @{
        var pageTitle = "ABCÅÄÖåäöÜü123";
    }
    
    <title>@Html.Raw(@pageTitle) </title>
    <title>@pageTitle</title>`

This is the result for Html.Raw 

`<title>ABCÅÄÖåäöÜü123 </title>`

And this for the plain text 
`<title>ABC&#xC5;&#xC4;&#xD6;&#xE5;&#xE4;&#xF6;&#xDC;&#xFC;123</title>`

Maybe thats worth a try

**Comment by sebnilsson** [comment]
Leaving the strings completely raw is probably not the expected behavior for the majority of the users.

There probably needs to be some kind of minimal encoding of values.
